### PR TITLE
WIP: ADD: using pre-commit for code quality

### PR DESCRIPTION
**Pull request by afunTW**
## ADD

- `pre-commit`: trigger the check process when committing locally
- `isort`: comply with the convention of importing the python package
- `black`: code auto formatter
    - rely on python 3.6
- `pydocstyle`: check the function documentation
    - check docstring existence
    - ignore the magic method
- others `pre-commit` hook
    - trailing whitespace
    - EOF fixer
    - YAML fixer

### CODE REVIEW

**Comment by afunTW** [comment]
two more modification

- python 3.5 allow failed
- pytest.mocker no need context manager
  - https://github.com/pytest-dev/pytest-mock#note-about-usage-as-context-manager

**Comment by bluet** [comment]
@afunTW 鄧來喔～～～ XDDD

**Comment by afunTW** [comment]
@bluet 看你的 CI 應該是有過，但是跟原版的不太一樣我還沒看

`requirements/base.txt` conflict 的部份只是多了一堆空白換行

**Comment by bluet** [comment]
@afunTW 所以直接放棄 3.5 對嗎 XD

話說好像有 conflict?

**Comment by afunTW** [comment]
我是放棄 python3.5 support ，然後 conflict 是你的 repo 中 `requirements/base.txt` 多一行空白行而已，看要哪邊改我都可以 XD

**Comment by afunTW** [comment]
https://github.com/bluet/proxybroker2/blob/master/requirements/base.txt
https://github.com/afunTW/proxybroker2/blob/master/requirements/base.txt

**Comment by bluet** [comment]
@afunTW ok hahaha

Up to you, as long as the conflict can be resolved then  I can merge it lol

**Comment by afunTW** [comment]
@bluet Consider my `pre-commit` setting will auto remove the last blank line at EOF, may I kindly recommend you to remove it in your repo?

**Comment by afunTW** [comment]
@bluet Done. Thanks for your suggestion.

`git pull https://github.com/bluet/proxybroker2.git master`

**Comment by bluet** [comment]
@afunTW thanks!

**Pull request merged**
