### PR TITLE
Remove deprecation warnings/Add support for python 3.10

### PR DESCRIPTION
**Pull request by ziloka**
Result
image

I'm not entirely sure how to remove the other deprecation warnings.
[DeprecationWarning: Using ioctl() method](https://github.com/python/cpython/issues/89111)
[asyncio DatagramProtocol stops calling callbacks after OSError](https://bugs.python.org/issue44743)

Related to:
#89

### CODE REVIEW

**Comment by ziloka** [comment]
the cli_helper function is there because asyncio event loop, run until complete function wants a coroutine. I followed this stackoverflow answer https://stackoverflow.com/questions/70303895/python-3-10-asyncio-gather-shows-deprecationwarning-there-is-no-current-event.

I'm no python expert so take my advice (and code) with a grain of salt

**Comment by bluet** [comment]
Hi @ziloka could you remove the redundant commented-out codes?

You can use comments as notes to describe something or FIXME, but not just as a recycle bin to keep old code. Thanks! :-)

**Comment by ziloka** [comment]
Got it

**Comment by bluet** [comment]
@ziloka can you sync from master or rebase?

**Comment by ziloka** [comment]
I synced with master

**Comment by vincentinttsh** [comment]
LGTM

**Comment by vincentinttsh** [comment]
https://github.com/bluet/proxybroker2/runs/7994487659?check_suite_focus=true#step:9:105
It seen that still get  DeprecationWarning in diffent file

**Comment by ziloka** [comment]
Okay, thanks for letting me know

**Comment by bluet** [comment]
@ziloka Thanks for the fix.

Looks like there are still few `DeprecationWarning: There is no current event loop` in "All checks have passed" > "build & test / build (3.8, 1.1.14) (pull request)" > "Details" > "Test with pytest". Will you be able to solve them?

Ref:
- https://github.com/bluet/proxybroker2/runs/8029099384?check_suite_focus=true#step:9:77

**Comment by ziloka** [comment]
Uh sorry i can't reproduce it 
image

**Comment by bluet** [comment]
@ziloka that's weird. I can still see those deprecation warnings in tests.

I'll merge it anyway but we might need to do some follow-ups.

**Pull request merged**
