### PR TITLE
Add coverage test

### PR DESCRIPTION
**Pull request by afunTW**
## Summary

Under the `pytest` framework with `pytest-cov` module, the output will be like the following message

```
---------- coverage: platform linux, python 3.8.10-final-0 -----------
Name                         Stmts   Miss  Cover
------------------------------------------------
proxybroker/__init__.py         22      0   100%
proxybroker/api.py             229    196    14%
proxybroker/checker.py         209    185    11%
proxybroker/errors.py           24      0   100%
proxybroker/judge.py            78     60    23%
proxybroker/negotiators.py      96      4    96%
proxybroker/providers.py       358    215    40%
proxybroker/proxy.py           217     58    73%
proxybroker/resolver.py         93     12    87%
proxybroker/server.py          245    218    11%
proxybroker/utils.py            83     22    73%
tests/__init__.py                0      0   100%
tests/conftest.py               49      6    88%
tests/test_negotiators.py       58      0   100%
tests/test_proxy.py            173      0   100%
tests/test_resolver.py          65      0   100%
tests/test_utils.py             24      0   100%
tests/utils.py                   8      0   100%
------------------------------------------------
TOTAL                         2031    976    52%
```

### CODE REVIEW

**Comment by afunTW** [comment]
I figure out that the CI flow all depends on `poetry.lock`, which should be define in `CONTRIBUTE.md`. The Ci failed because I updated the `requirements/` only

**Comment by bluet** [comment]
oops tests are failing https://github.com/bluet/proxybroker2/runs/7989566629?check_suite_focus=true#step:9:14

```
pytest: error: unrecognized arguments: --cov
```

**Comment by bluet** [comment]
LGTM

**Comment by hms5232** [comment]
> I figure out that the CI flow all depends on `poetry.lock`, which should be define in `CONTRIBUTE.md`. The Ci failed because I updated the `requirements/` only

related https://github.com/bluet/proxybroker2/issues/93#issuecomment-1225179188

**Pull request merged**
