### PR TITLE
Compile executables for major platforms using github actions

### PR DESCRIPTION
**Pull request by ziloka**
WIP: executable name specify use of operating system and architecture.

### CODE REVIEW

**Comment by ziloka** [comment]
Ok I dont know if this is ready tho. I feel like the commits are not in order or something. Besides that I think Im ready for this PR.

**Comment by bluet** [comment]
@ziloka  The generated files don't seem to work.

```
$ ./proxybroker-Linux-x86_64 --help
Traceback (most recent call last):
  File "py2exe_entrypoint.py", line 1, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "proxybroker/__init__.py", line 31, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "proxybroker/api.py", line 9, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "proxybroker/checker.py", line 16, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "proxybroker/judge.py", line 5, in <module>
ModuleNotFoundError: No module named 'aiohttp'
[122468] Failed to execute script 'py2exe_entrypoint' due to unhandled exception!
```

Maybe need to specify the module lookup path with `-p` or use `--hidden-import` with pyinstaller?

**Comment by ziloka** [comment]
Sorry, I just made a fix, it would be great if you would merge this

**Comment by bluet** [comment]
@ziloka thanks!

**Comment by ziloka** [comment]
This PR is ready fyi, i should've used the draft button.

**Comment by bluet** [comment]
Hi @ziloka there's a conflict file change. Might need to sync/merge/rebase from master branch.

BTW, is `.devcontainer/` necessary here?

**Comment by ziloka** [comment]
.dev container isn't necessary. it is for using a docker container as a development environment

**Comment by bluet** [comment]
@ziloka haha I know. Sorry what I really mean is, can you remove the `.devcontainer/` to avoid conflicts? :rofl:

**Comment by ziloka** [comment]
Sorry for the long delay, I made a commit to remove devcontainer configuration files but it seems like you need to do something on your end (those with write access) to resolve the conflict.. ?

**Comment by bluet** [comment]
@ziloka so nice to see you back!

I've removed existing `.devcontainer/`, can merge when all tests pass. :+1:

**Comment by ziloka** [comment]
> @ziloka so nice to see you back!
> 
> I've removed existing `.devcontainer/`, can merge when all tests pass. :+1: 

alright

**Pull request merged**
